version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8

  pre_build:
    commands:
      - echo Initializing environment
      - echo Getting AWS CodeArtifact auth token...
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token \
          --domain my-domain \
          --domain-owner 536765581091 \
          --query authorizationToken \
          --output text`

  build:
    commands:
      - echo Build started on `date`
      - mvn -s settings.xml compile 

  post_build:
    commands:
      - echo Build completed on `date`
      - mvn -s settings.xml package 

artifacts:
  files:
    - target/nextwork-web-project.war
  discard-paths: no